path:  /content/drive/MyDrive/Datasets/yolov8
train: images/train
val: images/val
test: images/test


#Classes
nc: 4 # replace according to your number of classes

#classes names
#replace all class names list with your classes names
names: 
  0: 'prohibitory'
  1: 'danger'
  2: 'mandatory'
  3: 'other'